[tool.poetry]
name = "dockerfiles"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
parse-emails = {git = "https://github.com/demisto/parse-emails.git", rev = "905dd1eb5ee8ac9ab64caadba7b410ba2a771696"}
rtfde = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
